#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output Virtual1 --mode 1920x1080 &
picom --no-fading-openclose &
feh --bg-scale /home/user/.config/bg/bground.png
light-locker &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
